version: '3.8'
services:
  application:
    image: docker.io/williamcustodio/guest-list-api:latest
    restart: unless-stopped
    container_name: guest-list-api
    environment:
      - APPLICATION_ARGS=-DDATA_SOURCE_URL=jdbc:mysql://database:3306/guest-list -DDATA_SOURCE_USERNAME=guest-list -DDATA_SOURCE_PASSWORD=guest-list -DLIQUIBASE_ENABLED=false
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql:5.7
    container_name: guest-list-api-database
    restart: unless-stopped
    environment:
      MYSQL_USER: guest-list
      MYSQL_PASSWORD: guest-list
      MYSQL_ROOT_PASSWORD: guest-list
      MYSQL_DATABASE: guest-list
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - "./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"